import React, { useEffect, useMemo, useState } from 'react';
import { Cloud, Cpu, HardDrive, RefreshCw, Trash2 } from 'lucide-react';
import type { RuntimeClient } from '../../runtime-client';
import type { ModelRecord } from '../../types';

type RouteState = { activeModelId: string | null; policy: string; fallbackModelIds: string[] };
interface Props { runtimeClient: RuntimeClient; onActiveModelChanged?: (modelId: string | null) => void }
const policies = ['LocalFirst', 'Balanced', 'Performance', 'Battery', 'Privacy', 'CloudAllowed', 'NeverCloud'] as const;

const SkeletonRow = () => <div className="flex items-center gap-3 rounded-xl border border-[var(--sori-border-soft)] p-4" aria-hidden="true"><div className="h-5 w-5 animate-pulse rounded-full bg-[var(--sori-fill-disabled)]" /><div className="h-8 w-8 animate-pulse rounded-lg bg-[var(--sori-fill-disabled)]" /><div className="min-w-0 flex-1 space-y-2"><div className="h-3 w-1/3 animate-pulse rounded bg-[var(--sori-fill-disabled)]" /><div className="h-3 w-2/3 animate-pulse rounded bg-[var(--sori-fill-disabled)]" /></div></div>;

export const ModelManagerScreen: React.FC<Props> = ({ runtimeClient, onActiveModelChanged }) => {
  const [models, setModels] = useState<ModelRecord[]>([]); const [route, setRoute] = useState<RouteState | null>(null); const [location, setLocation] = useState<'local' | 'cloud'>('local'); const [status, setStatus] = useState<'loading' | 'ready' | 'empty' | 'error'>('loading'); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [modelName, setModelName] = useState(''); const [artifactPath, setArtifactPath] = useState(''); const [whisperExecutable, setWhisperExecutable] = useState(''); const [whisperModelDir, setWhisperModelDir] = useState(''); const [checksum, setChecksum] = useState(''); const [installDetail, setInstallDetail] = useState<string | null>(null);
  const load = async () => { setStatus('loading'); setError(null); const [modelsResult, routeResult, configResult] = await Promise.all([runtimeClient.models(), runtimeClient.route<RouteState>(), runtimeClient.resource<{ executable?: string | null; model_dir?: string | null }>('whisper')]); if (modelsResult.error || routeResult.error) { setStatus('error'); setError(modelsResult.error ?? routeResult.error); return; } if (!configResult.error) { setWhisperExecutable(configResult.data?.executable ?? ''); setWhisperModelDir(configResult.data?.model_dir ?? ''); } const nextModels = Array.isArray(modelsResult.data) ? modelsResult.data : []; setModels(nextModels); setRoute(routeResult.data); onActiveModelChanged?.(routeResult.data.activeModelId ?? null); setStatus(nextModels.length ? 'ready' : 'empty'); };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => models.filter((model) => model.location === location), [models, location]);
  const selectModel = async (id: string) => { setSaving(true); const result = await runtimeClient.setActiveModel(id); if (result.error) setError(result.error); else await load(); setSaving(false); };
  const selectPolicy = async (policy: typeof policies[number]) => { setSaving(true); const result = await runtimeClient.setRoutePolicy(policy); if (result.error) setError(result.error); else await load(); setSaving(false); };
  const lifecycle = async (model: ModelRecord, operation: 'load' | 'warm' | 'unload') => { setSaving(true); setError(null); const result = await (operation === 'load' ? runtimeClient.loadModel(model.id) : operation === 'warm' ? runtimeClient.warmModel(model.id) : runtimeClient.unloadModel(model.id)); if (result.error) setError(result.error); else await load(); setSaving(false); };
  const removeModel = async (model: ModelRecord) => { if (route?.activeModelId === model.id) return; setSaving(true); setError(null); const result = await runtimeClient.removeModel(model.id); if (result.error) setError(result.error); else await load(); setSaving(false); };
  const importModel = async () => { const name = modelName.trim(); const source = artifactPath.trim(); const digest = checksum.trim(); if (!name || !source || !/^[0-9a-fA-F]{64}$/.test(digest)) { setInstallDetail('Import requires a model filename, an existing local artifact path, and its 64-character SHA-256 checksum.'); return; } setSaving(true); setError(null); setInstallDetail('Verifying checksum and importing the user-owned artifact…'); const operation = runtimeClient.installModel(name, source, digest); const poll = window.setInterval(() => { void runtimeClient.modelStatus(name).then((result) => { const current = result.data as { status?: { progress_percent?: number | null; phase?: string | null } } | null; const percent = current?.status?.progress_percent; const phase = current?.status?.phase ?? 'provider'; if (!result.error && typeof percent === 'number') setInstallDetail(`Importing… ${percent}% (${phase})`); }); }, 250); const result = await operation; window.clearInterval(poll); if (result.error) { setError(result.error); setInstallDetail('Import failed; no model was selected or reported ready.'); } else { setInstallDetail('Import completed. Readiness below is reported by the configured provider.'); setModelName(''); setArtifactPath(''); setChecksum(''); await load(); } setSaving(false); };
  const saveRuntimeConfig = async () => { setSaving(true); setError(null); const result = await runtimeClient.setResource('whisper', { executable: whisperExecutable.trim(), model_dir: whisperModelDir.trim() || null }); if (result.error) setError(result.error); else setInstallDetail('Runtime paths saved. Restart sorid to rediscover the configured executable and models.'); setSaving(false); };

  return <main className="sori-screen sori-page-layout sori-screen-models space-y-6" aria-busy={status === 'loading'}>
    <header><h1 className="sori-page-heading">Models &amp; routing</h1><p className="sori-body-text mt-1">Choose the active model and routing policy.</p></header>
    {error && <div role="alert" className="flex items-start justify-between gap-4 rounded-lg border border-[var(--sori-error-border)] bg-[var(--sori-error-bg)] p-4 text-sm text-[var(--sori-error-text)]"><span>{error}</span><button className="shrink-0 font-medium underline" onClick={() => void load()}>Retry</button></div>}
    <section className="sori-pane space-y-5 p-4" aria-labelledby="active-route-heading">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--sori-border-soft)] pb-4"><div><h2 id="active-route-heading" className="sori-section-heading">Active route</h2><p className="sori-meta-text mt-1" aria-live="polite">{route ? `${route.policy} · ${route.activeModelId ?? 'No model selected'}` : 'Loading route…'}</p></div><button className="sori-tactile-btn rounded-lg px-3 py-2 text-xs" onClick={() => void load()} disabled={status === 'loading'}><RefreshCw className="mr-1 inline h-4 w-4" aria-hidden="true"/>Refresh</button></div>
      <div className="flex flex-wrap gap-2" role="group" aria-label="Routing policy">{policies.map((policy) => <button key={policy} className={`rounded-lg border px-2.5 py-1 text-xs ${route?.policy === policy ? 'border-[var(--sori-accent-primary-border)] bg-[var(--sori-fill-selected)] font-medium' : 'border-[var(--sori-border-soft)] text-[var(--sori-text-secondary)]'}`} aria-pressed={route?.policy === policy} disabled={saving} onClick={() => void selectPolicy(policy)}>{policy}</button>)}</div>
      <div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-[var(--sori-border-soft)] bg-[var(--sori-bg-panel-subtle)] p-4 space-y-3"><div><h3 className="text-sm font-medium">Whisper runtime paths</h3><p className="sori-meta-text mt-1">Changes apply after restarting sorid.</p></div><label className="block text-xs text-[var(--sori-text-secondary)]">Executable path<input aria-label="Whisper executable path" className="mt-1 w-full rounded-lg border border-[var(--sori-border-default)] bg-[var(--sori-bg-panel)] p-2 text-xs" placeholder="whisper-cli.exe path" value={whisperExecutable} onChange={(event) => setWhisperExecutable(event.target.value)} /></label><label className="block text-xs text-[var(--sori-text-secondary)]">Model directory<input aria-label="Whisper model directory" className="mt-1 w-full rounded-lg border border-[var(--sori-border-default)] bg-[var(--sori-bg-panel)] p-2 text-xs" placeholder="Whisper model directory" value={whisperModelDir} onChange={(event) => setWhisperModelDir(event.target.value)} /></label><button type="button" className="sori-tactile-btn rounded-lg px-3 py-2 text-xs disabled:opacity-50" disabled={saving} onClick={() => void saveRuntimeConfig()}>Save runtime paths</button></div>
      <div className="rounded-xl border border-[var(--sori-border-soft)] bg-[var(--sori-bg-panel-subtle)] p-4 space-y-3"><div><h3 className="text-sm font-medium">Import a Whisper model</h3><p className="sori-meta-text mt-1">Choose a local file and provide its SHA-256 checksum.</p></div><label className="block text-xs text-[var(--sori-text-secondary)]">Model filename<input aria-label="Model filename" className="mt-1 w-full rounded-lg border border-[var(--sori-border-default)] bg-[var(--sori-bg-panel)] p-2 text-xs" placeholder="ggml-base.en.bin" value={modelName} onChange={(event) => setModelName(event.target.value)} /></label><label className="block text-xs text-[var(--sori-text-secondary)]">Artifact path<input aria-label="Model artifact path" className="mt-1 w-full rounded-lg border border-[var(--sori-border-default)] bg-[var(--sori-bg-panel)] p-2 text-xs" placeholder="Local artifact path" value={artifactPath} onChange={(event) => setArtifactPath(event.target.value)} /></label><label className="block text-xs text-[var(--sori-text-secondary)]">SHA-256 checksum<input aria-label="Model SHA-256 checksum" className="mt-1 w-full rounded-lg border border-[var(--sori-border-default)] bg-[var(--sori-bg-panel)] p-2 text-xs" placeholder="64-character checksum" value={checksum} onChange={(event) => setChecksum(event.target.value)} /></label><button type="button" className="sori-tactile-btn rounded-lg px-3 py-2 text-xs disabled:opacity-50" disabled={saving} onClick={() => void importModel()}>{saving ? 'Importing…' : 'Import and verify model'}</button>{installDetail && <p role="status" className="text-xs text-[var(--sori-text-secondary)]">{installDetail}</p>}</div></div>
      <div className="flex gap-4 border-b border-[var(--sori-border-soft)]"><button aria-pressed={location === 'local'} className={`border-b-2 pb-2 text-sm ${location === 'local' ? 'border-[var(--sori-accent-primary)] font-semibold' : 'border-transparent text-[var(--sori-text-secondary)]'}`} onClick={() => setLocation('local')}><HardDrive className="mr-1 inline h-4 w-4" aria-hidden="true"/>Local<span className="sr-only"> models</span></button><button aria-pressed={location === 'cloud'} className={`border-b-2 pb-2 text-sm ${location === 'cloud' ? 'border-[var(--sori-accent-primary)] font-semibold' : 'border-transparent text-[var(--sori-text-secondary)]'}`} onClick={() => setLocation('cloud')}><Cloud className="mr-1 inline h-4 w-4" aria-hidden="true"/>Cloud<span className="sr-only"> models</span></button></div>
      <div aria-live="polite">{status === 'loading' && <div className="space-y-2" aria-label="Loading models"><SkeletonRow/><SkeletonRow/></div>}{status === 'empty' && <div className="rounded-xl border border-dashed border-[var(--sori-border-default)] p-8 text-center text-sm text-[var(--sori-text-secondary)]">No models are registered by sorid. Import a user-owned artifact or configure the runtime before selecting a route.</div>}{status === 'ready' && !visible.length && <div className="rounded-xl border border-dashed border-[var(--sori-border-default)] p-8 text-center text-sm text-[var(--sori-text-secondary)]">No {location} models are registered. Cloud routing does not send requests without a configured provider.</div>}</div>
      {status === 'ready' && visible.length > 0 && <div className="space-y-2">{visible.map((model) => { const active = route?.activeModelId === model.id; return <div key={model.id} className={`flex flex-wrap items-center gap-3 rounded-xl border p-4 ${active ? 'border-[var(--sori-accent-primary-border)] bg-[var(--sori-fill-selected)]' : 'border-[var(--sori-border-soft)]'}`}><button aria-label={`Select ${model.name}`} aria-pressed={active} disabled={!model.available || saving} onClick={() => void selectModel(model.id)} className={`h-5 w-5 rounded-full border-2 ${active ? 'border-[var(--sori-accent-primary)] bg-[var(--sori-accent-primary)] shadow-[inset_0_0_0_3px_var(--sori-bg-panel)]' : 'border-[var(--sori-border-strong)]'}`}/><Cpu className="h-8 w-8 rounded-lg bg-[var(--sori-bg-panel)] p-2 text-[var(--sori-accent-primary)]" aria-hidden="true"/><div className="min-w-0 flex-1"><div className="text-sm font-medium">{model.name} {model.recommended && <span className="ml-2 rounded-full bg-[var(--sori-accent-primary-soft)] px-2 py-0.5 text-[10px]">Recommended</span>}</div><div className="sori-meta-text">{model.provider} · {model.available ? 'Available' : model.unavailableReason ?? 'Unavailable'} · {model.warm ? 'Warm' : model.loaded ? 'Loaded' : 'Not loaded'}</div><div className="sori-meta-text mt-1 break-all">{model.sha256 ? `SHA-256 ${model.sha256}` : 'SHA-256 unavailable'} · {model.license ?? 'License/source not declared'}{model.source ? ` · Source ${model.source}` : ''}</div></div><span className="text-[11px] text-[var(--sori-text-secondary)]">{model.qualityTier}</span><div className="flex gap-1"><button type="button" disabled={!model.available || saving} onClick={() => void lifecycle(model, model.warm ? 'unload' : 'warm')} className="sori-tactile-btn rounded-lg px-2 py-1 text-[11px] disabled:opacity-40">{model.warm ? 'Unload' : 'Warm'}</button><button type="button" aria-label={`Delete ${model.name}`} disabled={active || saving} onClick={() => void removeModel(model)} className="sori-tactile-btn rounded-lg p-2 text-[var(--sori-error-text)] disabled:cursor-not-allowed disabled:opacity-40"><Trash2 className="h-3.5 w-3.5" aria-hidden="true"/></button></div></div>; })}</div>}
    </section>
  </main>;
};
