import React, { useMemo, useState } from 'react';
import { ChevronRight, CirclePlus, Cloud, Cpu, HardDrive, SlidersHorizontal } from 'lucide-react';
import { ModelInfo, RouteRule } from '../../types';

interface Props { models: ModelInfo[]; setModels: React.Dispatch<React.SetStateAction<ModelInfo[]>>; routes: RouteRule[]; setRoutes: React.Dispatch<React.SetStateAction<RouteRule[]>>; }
const providers = ['All Models', 'OpenAI', 'Anthropic', 'Gemini', 'Groq', 'Custom'];
const cloudModels = [
  { id: 'whisper-large-v3', name: 'Whisper Large v3', provider: 'OpenAI', detail: 'Highest accuracy · Best for general use', tier: 'High Quality' },
  { id: 'gpt-4o-transcribe', name: 'gpt-4o-transcribe', provider: 'OpenAI', detail: 'Complex audio and diarization', tier: 'Ultra' },
  { id: 'gemini-1.5-pro-audio', name: 'Gemini 1.5 Pro (Audio)', provider: 'Gemini', detail: 'Multilingual · Strong performance', tier: 'High Quality' },
  { id: 'claude-3.5-sonnet-audio', name: 'Claude 3.5 Sonnet (Audio)', provider: 'Anthropic', detail: 'Advanced reasoning · Context aware', tier: 'High Quality' },
];

export const ModelManagerScreen: React.FC<Props> = ({ models, setModels, routes, setRoutes }) => {
  const [tab, setTab] = useState<'models' | 'routes'>('models');
  const [location, setLocation] = useState<'cloud' | 'local'>('local');
  const [provider, setProvider] = useState('All Models');
  const [selected, setSelected] = useState(models.find((m) => m.isWarm)?.id ?? '');
  const [details, setDetails] = useState<string | null>(null);
  const [customOpen, setCustomOpen] = useState(false);
  const visible = useMemo(() => models.filter((m) => location === 'local' ? m.backend !== 'Cloud API' : false), [models, location]);
  const selectLocal = (id: string) => { setSelected(id); setModels((current) => current.map((m) => ({ ...m, isWarm: m.id === id }))); };
  return <div className="mx-auto max-w-5xl space-y-6 p-4 md:p-8">
    <header><h1 className="sori-page-heading">Models &amp; Routing</h1><p className="sori-body-text mt-1">Choose where Sori processes speech and which models power each task.</p></header>
    <div className="mx-auto flex max-w-xl rounded-2xl bg-[#EEEAE4] p-1.5"><button className={`flex-1 rounded-xl py-2 text-sm ${tab === 'models' ? 'bg-[#FFFDF9] shadow-sm font-semibold' : 'text-[#68635D]'}`} onClick={() => setTab('models')}>Speech &amp; Models</button><button className={`flex-1 rounded-xl py-2 text-sm ${tab === 'routes' ? 'bg-[#FFFDF9] shadow-sm font-semibold' : 'text-[#68635D]'}`} onClick={() => setTab('routes')}>Routes &amp; Triggers</button></div>
    {tab === 'routes' ? <section className="sori-pane space-y-4 p-5"><div><h2 className="sori-section-heading">Routing rules</h2><p className="sori-body-text mt-1">Rules are currently local UI state. Daemon route mutation is <b>Needs Wiring</b>.</p></div>{routes.map((route) => <div key={route.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E5E0D9] py-3"><div><div className="text-sm font-medium">{route.condition}</div><div className="sori-meta-text">→ {route.targetModel} · priority {route.priority}</div></div><button className="sori-tactile-btn rounded-lg px-3 py-1.5 text-xs" aria-pressed={route.enabled} onClick={() => setRoutes((current) => current.map((r) => r.id === route.id ? { ...r, enabled: !r.enabled } : r))}>{route.enabled ? 'Enabled' : 'Disabled'}</button></div>)}</section> : <section className="sori-pane space-y-5 p-5">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E5E0D9] pb-4"><div className="flex gap-4"><button className={`border-b-2 pb-2 text-sm ${location === 'cloud' ? 'border-[#6E7A80] font-semibold' : 'border-transparent text-[#68635D]'}`} onClick={() => setLocation('cloud')}><Cloud className="mr-1 inline h-4 w-4"/>Cloud</button><button className={`border-b-2 pb-2 text-sm ${location === 'local' ? 'border-[#6E7A80] font-semibold' : 'border-transparent text-[#68635D]'}`} onClick={() => setLocation('local')}><HardDrive className="mr-1 inline h-4 w-4"/>Local</button></div><button className="sori-tactile-btn rounded-lg px-3 py-2 text-xs" onClick={() => setCustomOpen(true)}><CirclePlus className="mr-1 inline h-4 w-4"/>Add Custom Model</button></div>
      {location === 'cloud' && <div className="rounded-lg border border-[#EBD9A8] bg-[#FFF7E6] p-3 text-xs text-[#6B552C]">Cloud providers are visible for configuration, but API key and model selection IPC are <b>Unavailable</b>. No cloud request will be sent.</div>}
      <div className="flex flex-wrap gap-2">{providers.map((p) => <button key={p} className={`rounded-full border px-3 py-1.5 text-xs ${provider === p ? 'bg-[#ECEEEB] border-[#B9C0BF] font-medium' : 'border-[#E5E0D9] text-[#68635D]'}`} onClick={() => setProvider(p)}>{p}</button>)}</div>
      <div className="space-y-2">{(location === 'local' ? visible : cloudModels).filter((m: any) => provider === 'All Models' || m.provider === provider).map((m: any) => { const active = selected === m.id; return <div key={m.id} className={`flex items-center gap-3 rounded-xl border p-3.5 ${active ? 'bg-[#F2EEE8] border-[#C9C1B7]' : 'border-[#E5E0D9]'}`}><button aria-label={`Select ${m.name}`} aria-pressed={active} onClick={() => location === 'local' ? selectLocal(m.id) : setDetails(m.id)} className={`h-5 w-5 rounded-full border-2 ${active ? 'border-[#6E7A80] bg-[#6E7A80] shadow-[inset_0_0_0_3px_#FFFDF9]' : 'border-[#C9C1B7]'}`}/><Cpu className="h-8 w-8 rounded-lg bg-[#FFFDF9] p-2 text-[#6E7A80]"/><div className="min-w-0 flex-1"><div className="text-sm font-medium">{m.name} {m.recommended && <span className="ml-2 rounded-full bg-[#ECEEEB] px-2 py-0.5 text-[10px]">Recommended</span>}</div><div className="sori-meta-text">{m.provider ?? m.backend} · {m.detail ?? m.description}</div></div><span className="rounded-full border border-[#E5E0D9] px-2.5 py-1 text-[11px]">{m.tier ?? m.speedRating}</span><button aria-label={`View details for ${m.name}`} onClick={() => setDetails(m.id)}><ChevronRight className="h-4 w-4 text-[#98928A]"/></button></div>})}</div>
      {location === 'local' && visible.length === 0 && <div className="p-8 text-center text-sm text-[#68635D]">No local models available. Check Diagnostics or add a custom model.</div>}
    </section>}
    {details && <div className="sori-overlay fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-[#FFFDF9] p-6"><h2 className="sori-section-heading">Model details</h2><p className="sori-body-text mt-2">{details}</p><p className="mt-4 text-xs text-[#9A7442]">Selection persistence is Needs Wiring until the canonical model IPC operation exists.</p><button className="sori-tactile-btn mt-6 rounded-lg px-4 py-2 text-sm" onClick={() => setDetails(null)}>Close</button></div></div>}
    {customOpen && <div className="sori-overlay fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog"><form className="w-full max-w-md rounded-2xl bg-[#FFFDF9] p-6" onSubmit={(e) => { e.preventDefault(); setCustomOpen(false); }}><h2 className="sori-section-heading">Add custom model</h2><label className="mt-4 block text-xs font-medium">Model name<input required className="sori-control mt-1 w-full rounded-lg p-2" placeholder="e.g. Whisper Large v3 local"/></label><p className="mt-3 text-xs text-[#9A7442]">This form is a local preview. Model repository and download IPC are <b>Needs Wiring</b>.</p><div className="mt-5 flex justify-end gap-2"><button type="button" className="px-3 py-2 text-sm" onClick={() => setCustomOpen(false)}>Cancel</button><button className="sori-tactile-btn rounded-lg px-4 py-2 text-sm">Save preview</button></div></form></div>}
  </div>;
};