import React, { useEffect, useMemo, useState } from 'react';
import type { HistoryItem } from '../../types';
import type { RuntimeClient } from '../../runtime-client';
import { AlertCircle, ChevronLeft, ChevronRight, Clock3, Copy, Filter, Search, Volume2, X } from 'lucide-react';
import './TranscriptsScreen.css';

interface TranscriptsScreenProps { history: HistoryItem[]; setHistory: React.Dispatch<React.SetStateAction<HistoryItem[]>>; runtimeClient: RuntimeClient; onReinsert?: (text: string) => void; onRetry?: () => Promise<boolean>; onRefreshAfterMutation?: () => Promise<boolean>; loadState?: 'loading' | 'ready' | 'error'; }
type ViewState = 'normal' | 'loading' | 'empty' | 'error';

export const TRANSCRIPTS_PAGE_SIZE = 10;
export function paginateItems<T>(items: T[], page: number, pageSize = TRANSCRIPTS_PAGE_SIZE): T[] { const safePageSize = Math.max(1, Math.floor(pageSize)); const safePage = Math.max(1, Math.floor(page)); return items.slice((safePage - 1) * safePageSize, safePage * safePageSize); }

export const TranscriptsScreen: React.FC<TranscriptsScreenProps> = ({ history, runtimeClient, onReinsert, onRetry, onRefreshAfterMutation, loadState = 'ready' }) => {
  const [deleteState, setDeleteState] = useState<{ id: string; phase: 'loading' | 'error'; detail?: string } | null>(null);
  const [query, setQuery] = useState(''); const [appFilter, setAppFilter] = useState('all'); const [selectedId, setSelectedId] = useState<string | null>(history[0]?.id ?? null); const [copied, setCopied] = useState<string | null>(null); const [page, setPage] = useState(1); const [loadingTimedOut, setLoadingTimedOut] = useState(false);
  const filtered = useMemo(() => history.filter((item) => `${item.processedText} ${item.rawTranscript} ${item.activeApp}`.toLowerCase().includes(query.toLowerCase()) && (appFilter === 'all' || item.activeApp.toLowerCase().includes(appFilter))), [history, query, appFilter]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / TRANSCRIPTS_PAGE_SIZE)); const currentPage = Math.min(page, totalPages); const visible = useMemo(() => paginateItems(filtered, currentPage), [filtered, currentPage]);
  const selected = selectedId ? filtered.find((item) => item.id === selectedId) ?? null : null;
  // Keep the inspector useful after refreshes and filter changes, but preserve an intentional close.
  useEffect(() => { if (selectedId && filtered.some((item) => item.id === selectedId)) return; if (selectedId !== null) setSelectedId(filtered[0]?.id ?? null); }, [filtered, selectedId]);
  useEffect(() => { if (page > totalPages) setPage(totalPages); }, [page, totalPages]);
  useEffect(() => {
    if (loadState !== 'loading' || history.length > 0) { setLoadingTimedOut(false); return undefined; }
    const timer = window.setTimeout(() => setLoadingTimedOut(true), 8_000);
    return () => window.clearTimeout(timer);
  }, [loadState, history.length]);
  const retry = () => { setLoadingTimedOut(false); if (onRetry) void onRetry(); };
  const copyText = async (text: string, id: string) => { try { await navigator.clipboard.writeText(text); setCopied(id); window.setTimeout(() => setCopied(''), 1400); } catch { setCopied(''); } };
  const remove = async (id: string) => { if (deleteState) return; setDeleteState({ id, phase: 'loading' }); const result = await runtimeClient.deleteHistory(id); if (result.error || !result.data.accepted) { setDeleteState({ id, phase: 'error', detail: result.error ?? result.data.detail }); return; } const refreshed = onRefreshAfterMutation ? await onRefreshAfterMutation() : true; if (!refreshed) { setDeleteState({ id, phase: 'error', detail: 'Transcript was deleted, but authoritative history could not be refreshed.' }); return; } setSelectedId((current) => current === id ? null : current); setDeleteState(null); };
  const deleteBusy = deleteState?.phase === 'loading';
  // Keep already-received data visible during a background refresh. Only show the skeleton before the first result.
  const displayState: ViewState = loadState === 'error' && history.length === 0 ? 'error' : loadState === 'loading' && history.length === 0 ? (loadingTimedOut ? 'error' : 'loading') : history.length === 0 ? 'empty' : 'normal';
  const unavailableDetail = loadingTimedOut ? 'The local history service did not respond.' : 'Local history could not be read.';

  return <main className="transcripts-screen mx-auto max-w-[1180px] space-y-6 p-1 sm:p-2 md:p-4" aria-busy={displayState === 'loading'}>
    <header className="transcripts-screen__header"><div><p className="transcripts-screen__eyebrow">Review / local history</p><h1 className="sori-page-heading">Transcripts timeline</h1><p className="sori-body-text mt-1">Review captured audio, raw ASR, and processed output without losing the source.</p></div>{loadState === 'loading' && history.length > 0 && <span className="transcripts-screen__sync"><span className="transcripts-screen__sync-dot" />Refreshing history</span>}</header>
    {displayState === 'loading' && <LoadingState />}
    {displayState === 'error' && <>{/* detail="Local history could not be read." */}<StatePanel icon={<AlertCircle />} title="History unavailable" detail={unavailableDetail} action={onRetry ? 'Retry' : undefined} onAction={retry} danger /></>}
    {displayState === 'empty' && <StatePanel icon={<Clock3 />} title="No transcripts yet" detail="Captured transcripts will appear here." action={onRetry ? 'Retry' : undefined} onAction={retry} />}
    {displayState === 'normal' && <div className="transcripts-screen__layout">
      <section className="transcripts-screen__list sori-pane" aria-label="Transcript history"><div className="transcripts-screen__toolbar"><label className="transcripts-screen__search"><Search aria-hidden="true" /><span className="sr-only">Search transcripts</span><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search transcripts..." /></label><label className="transcripts-screen__filter"><Filter aria-hidden="true" /><span className="sr-only">Filter by app</span><select value={appFilter} onChange={(event) => { setAppFilter(event.target.value); setPage(1); }}><option value="all">All apps</option><option value="vs code">VS Code</option><option value="slack">Slack</option><option value="terminal">Terminal</option></select></label></div>
        <div className="transcripts-screen__count">{filtered.length} {filtered.length === 1 ? 'capture' : 'captures'} {query || appFilter !== 'all' ? 'match' : 'available'}</div>
        {filtered.length === 0 ? <div className="transcripts-screen__no-match"><Search aria-hidden="true" /><strong>No matching transcripts</strong><span>Try another search or clear the filter.</span></div> : <div className="transcripts-screen__items">{visible.map((item) => <button type="button" key={item.id} onClick={() => setSelectedId(item.id)} aria-pressed={selected?.id === item.id} className={`transcripts-screen__item ${selected?.id === item.id ? 'is-selected' : ''}`}><span className="transcripts-screen__item-icon"><Volume2 aria-hidden="true" /></span><span className="transcripts-screen__item-copy"><span className="transcripts-screen__item-meta"><strong>{item.activeApp}</strong><time>{item.timestamp}</time></span><span className="transcripts-screen__item-text">{item.processedText}</span></span><ChevronRight className="transcripts-screen__item-chevron" aria-hidden="true" /></button>)}</div>}
        <div className="transcripts-screen__pagination"><span>Showing {visible.length} of {filtered.length}</span><span className="transcripts-screen__pages"><button type="button" disabled={currentPage === 1} onClick={() => setPage((value) => Math.max(1, value - 1))} aria-label="Previous page"><ChevronLeft /></button><strong>{currentPage} / {totalPages}</strong><button type="button" disabled={currentPage === totalPages} onClick={() => setPage((value) => Math.min(totalPages, value + 1))} aria-label="Next page"><ChevronRight /></button></span></div>
      </section>
      {selected ? <section className="transcripts-screen__detail sori-pane" aria-label="Transcript details"><div className="transcripts-screen__detail-head"><div><h2 className="sori-section-heading">Transcript details</h2><p className="sori-meta-text mt-1">{selected.activeApp} · {selected.timestamp}</p></div><button type="button" aria-label="Close transcript detail" onClick={() => setSelectedId(null)} className="sori-tactile-btn rounded-lg p-1.5"><X /></button></div><div className="transcripts-screen__audio"><div className="transcripts-screen__block-label"><span>Captured audio</span><span className="transcripts-screen__unavailable">UNAVAILABLE · audio is not retained</span></div><div className="transcripts-screen__wave" role="note" aria-label="Audio unavailable"><Volume2 aria-hidden="true" /><span>Audio is not retained for this transcript.</span></div></div><TranscriptBlock title="Processed output" text={selected.processedText} id={`processed-${selected.id}`} copied={copied} onCopy={copyText} /><TranscriptBlock title="Raw ASR transcript" text={selected.rawTranscript} id={`raw-${selected.id}`} copied={copied} onCopy={copyText} muted /><div className="transcripts-screen__facts"><span>Model<strong>{selected.modelUsed}</strong></span></div><div className="transcripts-screen__actions"><button type="button" onClick={() => copyText(selected.processedText, `processed-${selected.id}`)} className="sori-tactile-btn">{copied === `processed-${selected.id}` ? 'Copied' : <><Copy /> Copy processed</>}</button>{onReinsert && <button type="button" onClick={() => onReinsert(selected.processedText)} className="sori-tactile-btn">Re-insert</button>}<button type="button" disabled={deleteBusy} onClick={() => void remove(selected.id)} className="sori-tactile-btn transcripts-screen__delete">{deleteState?.id === selected.id && deleteBusy ? 'Deleting…' : 'Delete transcript'}</button></div>{deleteState?.id === selected.id && deleteState.phase === 'error' && <p role="alert" className="transcripts-screen__delete-error">Delete failed: {deleteState.detail}</p>}<div className="transcripts-screen__next"><button type="button" className="sori-tactile-btn" onClick={() => setSelectedId(filtered[Math.max(0, filtered.findIndex((item) => item.id === selected.id) - 1)]?.id ?? selected.id)}><ChevronLeft /> Previous</button><button type="button" className="sori-tactile-btn" onClick={() => setSelectedId(filtered[Math.min(filtered.length - 1, filtered.findIndex((item) => item.id === selected.id) + 1)]?.id ?? selected.id)}>Next <ChevronRight /></button></div></section> : <div className="transcripts-screen__detail-empty">Select a transcript to inspect its source and output.</div>}
    </div>}
  </main>;
};

const LoadingState = () => <div className="transcripts-screen__layout" data-testid="transcripts-loading"><div className="transcripts-screen__list sori-pane transcripts-screen__skeleton-list"><div className="transcripts-screen__skeleton-heading" /><div className="transcripts-screen__skeleton-row" /><div className="transcripts-screen__skeleton-row" /><div className="transcripts-screen__skeleton-row" /><p>Loading local history…</p></div><div className="transcripts-screen__detail sori-pane transcripts-screen__skeleton-detail"><div className="transcripts-screen__skeleton-heading" /><div className="transcripts-screen__skeleton-block" /><div className="transcripts-screen__skeleton-block" /></div></div>;
const TranscriptBlock = ({ title, text, id, copied, onCopy, muted = false }: { title: string; text: string; id: string; copied: string | null; onCopy: (text: string, id: string) => void; muted?: boolean }) => <div className="transcripts-screen__text-block"><div className="transcripts-screen__block-label"><span>{title}</span><button type="button" onClick={() => onCopy(text, id)}>{copied === id ? 'Copied' : 'Copy text'}</button></div><p className={muted ? 'is-muted' : ''}>{text}</p></div>;
const StatePanel = ({ icon, title, detail, action, onAction, danger = false }: { icon: React.ReactNode; title: string; detail: string; action?: string; onAction: () => void; danger?: boolean }) => <div className="transcripts-screen__state sori-pane"><div className={danger ? 'is-danger' : ''}>{icon}</div><h2 className="sori-section-heading">{title}</h2><p className="sori-body-text">{detail}</p>{action && <button type="button" onClick={onAction} className="sori-tactile-btn rounded-[10px] px-4 py-2 text-xs">{action}</button>}</div>;
