import React, { useState } from 'react';
import { AppSettings } from '../../types';
import { AlertTriangle, Check, CheckCircle2, ChevronRight, Eye, FileCode2, LoaderCircle, Play, RotateCcw, Sparkles, X } from 'lucide-react';

interface VoiceEditScreenProps { settings: AppSettings; runtimeSource?: 'native' | 'backend' | 'mock' | 'unavailable'; }
type EditState = 'selection' | 'processing' | 'diff' | 'low-confidence' | 'no-selection' | 'blocked' | 'error' | 'applied';
const prompts = ['Add error handling and preserve the return type.', 'Rename this function and update its callers.', 'Convert this block to async and add a docstring.'];

export const VoiceEditScreen: React.FC<VoiceEditScreenProps> = ({ settings, runtimeSource = 'unavailable' }) => {
  const [instruction, setInstruction] = useState(prompts[0]); const [state, setState] = useState<EditState>('diff'); const connected = runtimeSource === 'native' || runtimeSource === 'backend';
  const canInject = connected && state === 'diff';
  const runPreview = () => { setState('processing'); window.setTimeout(() => setState('diff'), 450); };
  const accept = () => { if (!connected) { setState('blocked'); return; } setState('applied'); };
  return <div className="mx-auto max-w-[1180px] space-y-6 p-1 text-[#1C1B19] sm:p-2 md:p-4"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[11px] font-medium uppercase tracking-[0.16em] text-[#98928A]">Review before action</p><h1 className="sori-page-heading">Voice selection edit</h1><p className="sori-body-text mt-1">Review the parsed instruction and diff before anything touches the focused application.</p></div><div className="flex gap-2"><button type="button" onClick={runPreview} disabled={state === 'processing'} className="sori-tactile-btn rounded-[10px] px-3 py-2 text-xs"><Eye className="mr-1.5 inline h-3.5 w-3.5" />Preview in editor</button><button type="button" onClick={accept} disabled={state === 'processing' || state === 'applied'} className={`rounded-[10px] px-4 py-2 text-xs font-medium ${canInject ? 'bg-[#1C1B19] text-[#FFFDF9]' : 'sori-tactile-btn'}`}><Check className="mr-1.5 inline h-3.5 w-3.5" />Accept & inject</button></div></header>
    <div className="grid gap-5 lg:grid-cols-[minmax(340px,0.85fr)_minmax(0,1.35fr)]"><section className="rounded-[18px] border border-[rgba(92,84,75,0.13)] bg-[#FBF9F6] p-5 shadow-[0_4px_18px_rgba(92,84,75,0.05)]"><div className="flex items-center justify-between border-b border-[rgba(92,84,75,0.08)] pb-4"><h2 className="sori-section-heading">Intent</h2><span className={`rounded-full px-2.5 py-1 text-[10px] ${state === 'low-confidence' ? 'bg-[#F5EEDC] text-[#9A7442]' : 'bg-[#EAF3ED] text-[#4E7A61]'}`}>{state === 'low-confidence' ? 'Low confidence' : 'Selection detected'}</span></div><div className="mt-4 rounded-[14px] border border-[rgba(92,84,75,0.1)] bg-[#FFFDF9] p-4"><div className="mb-2 flex items-center gap-2 text-xs font-medium"><FileCode2 className="h-4 w-4 text-[#6E7A80]" />VS Code · active window</div><p className="text-[11px] text-[#98928A]">src/api/userService.ts · 3 lines selected</p></div><label className="mt-5 block text-xs font-medium">You said<textarea value={instruction} onChange={(event) => { setInstruction(event.target.value); setState('diff'); }} rows={3} className="mt-2 w-full rounded-[12px] border border-[rgba(92,84,75,0.12)] bg-[#FFFDF9] p-3 text-sm leading-6 outline-none focus:border-[#6E7A80]" /></label><div className="mt-4 rounded-[14px] bg-[#F2EEE8] p-4"><p className="mb-3 text-xs font-medium">Parsed intent</p>{['Preserve existing behavior', 'Add the requested transformation', 'Keep the current return type'].map((item) => <p key={item} className="mb-2 flex items-center gap-2 text-[11px] text-[#68635D]"><CheckCircle2 className="h-3.5 w-3.5 text-[#4E7A61]" />{item}</p>)}<div className="mt-3 border-t border-[rgba(92,84,75,0.08)] pt-3 text-[11px] text-[#4E7A61]">Confidence: high · Model: {settings.activeProfile === 'Coding' ? 'Whisper Q5' : 'active route'}</div></div><div className="mt-5"><p className="mb-2 text-xs font-medium">Test transformations</p><div className="flex flex-wrap gap-2">{prompts.map((prompt) => <button type="button" key={prompt} onClick={() => { setInstruction(prompt); setState('diff'); }} className="sori-tactile-btn rounded-full px-3 py-1.5 text-[11px]">{prompt.slice(0, 24)}…</button>)}</div></div></section>
      <section className="min-w-0 rounded-[18px] border border-[rgba(92,84,75,0.13)] bg-[#FBF9F6] p-5 shadow-[0_4px_18px_rgba(92,84,75,0.05)]"><div className="flex items-center justify-between border-b border-[rgba(92,84,75,0.08)] pb-4"><div><h2 className="sori-section-heading">Diff preview</h2><p className="sori-meta-text mt-1">src/api/userService.ts · TypeScript</p></div><span className="font-mono text-[11px] text-[#4E7A61]">+2 · -1</span></div>{state === 'processing' ? <div className="flex min-h-[330px] flex-col items-center justify-center text-center"><LoaderCircle className="mb-3 h-6 w-6 animate-spin text-[#6E7A80]" /><p className="text-xs font-medium">Re-running the edit preview</p><p className="sori-meta-text mt-1">The diff will remain unapplied.</p></div> : <><div className="mt-4 overflow-x-auto rounded-[12px] border border-[rgba(92,84,75,0.1)] bg-[#FFFDF9] font-mono text-[12px] leading-6"><div className="border-b border-[rgba(92,84,75,0.08)] bg-[#F2EEE8] px-4 py-2 text-[11px] text-[#68635D]">Reviewable change</div><div className="p-4"><div>const response = await fetch(url);</div><div className="my-1 bg-[#FAEDEA] px-2 text-[#A75850]">− const data = await response.json();</div><div className="bg-[#EAF3ED] px-2 text-[#4E7A61]">+ try {'{'}</div><div className="bg-[#EAF3ED] px-2 text-[#4E7A61]">+   const data = await response.json();</div><div className="bg-[#EAF3ED] px-2 text-[#4E7A61]">+ {'}'} catch (error) {'{'}</div><div className="bg-[#EAF3ED] px-2 text-[#4E7A61]">+   console.error('Request failed', error);</div><div className="bg-[#EAF3ED] px-2 text-[#4E7A61]">+ {'}'}</div></div></div><div className="mt-4 flex items-start gap-2 rounded-[12px] bg-[#F2EEE8] p-3 text-[11px] text-[#68635D]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-[#9A7442]" />{state === 'blocked' || !connected ? 'Injection is unavailable until a real Sori runtime is connected. Preview remains unapplied.' : 'This edit will be sent to the focused editor only after explicit approval.'}</div>{state === 'applied' && <div role="status" className="mt-4 rounded-[12px] border border-[rgba(78,122,97,0.2)] bg-[#EAF3ED] p-3 text-xs text-[#4E7A61]"><Check className="mr-2 inline h-4 w-4" />Edit accepted by the connected runtime.</div>}<div className="mt-4 flex items-center justify-between"><span className="font-mono text-[11px] text-[#98928A]">{connected ? 'Runtime connected' : 'UNVERIFIED · injection unavailable'}</span><button type="button" onClick={runPreview} className="text-xs text-[#6E7A80]"><RotateCcw className="mr-1 inline h-3.5 w-3.5" />Re-run edit</button></div></>}</section></div>
  </div>;
};
